### ISSUE TITLE
Small problems with Dockerfile

### ISSUE THREAD

**Issue by jamesaoverton** [airr-knowledge/ak-schema#2]
I hit a weird problem where the GitHub Actions tests for PR #1 are passing, but the tests are failing for me locally inside Docker.

Commit ba75d413fb6cb423eb6a56ab96b5727372c4ea84 added a Dockerfile and instructions to the README. I think they're based on https://github.com/linkml/linkml-project-cookiecutter/pull/16. The instructions worked for me until I tried running `make test-python`, and then I got Python path errors.

1. `docker build . -t airrknowledge/ak-schema` copies the current directory to `/ak-schema` and installs
2. `docker run -v $PWD:/work -it airrknowledge/ak-schema bash` opens a terminal in `/work`
3. `make test-python` fails with `ModuleNotFoundError: No module named 'sqlalchemy'` and `ModuleNotFoundError: No module named 'linkml_runtime'` even though stuff like `make site` works fine.
4. if I `cd /ak-schema` and run `make test-python` it works, but `/ak-schema` is the copy from the `docker build` not the mounted volume from the `docker run`

So there's a mismatch between `docker build` installing stuff in `/ak-schema` and then `docker run` mounting the PWD to `/work`. I'm not sure how to resolve that.

**Comment by schristley** [comment]
The issue is that the dependencies aren't installed in the docker image, i.e. `make install` in the project directory. I tried putting a copy at `/ak-schema` then do `make install` with it, but poetry seems to create a random python virtualenv, so when you move over to `/work` for your local code, it creates a different virtualenv:

```
Creating virtualenv ak-schema-DJpFP61h-py3.9 in /root/.cache/pypoetry/virtualenvs
```

I need to look into poetry more to see if there is a way to control how the virtualenv is created.

**Comment by schristley** [comment]
[disabled use of virtualenv](https://github.com/airr-knowledge/ak-schema/commit/4cf78f4f9189840cd0c10950a8eeba1a1a345b82) for poetry seems to have resolved it.
